# Generated by Django 3.1.7 on 2021-04-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardiacrequested',
            old_name='A_3_brand',
            new_name='A_3A_brand',
        ),
        migrations.RenameField(
            model_name='cardiacrequested',
            old_name='A_3_descr',
            new_name='A_3A_descr',
        ),
        migrations.RenameField(
            model_name='cardiacrequested',
            old_name='A_3_qty',
            new_name='A_3A_qty',
        ),
        migrations.RenameField(
            model_name='cardiacrequested',
            old_name='A_3_name',
            new_name='A_3B_brand',
        ),
        migrations.RemoveField(
            model_name='cardiacrequested',
            name='request',
        ),
        migrations.AddField(
            model_name='cardiacrequested',
            name='A_3A_name',
            field=models.CharField(default='Blood glucose strip', max_length=500),
        ),
        migrations.AddField(
            model_name='cardiacrequested',
            name='A_3B_descr',
            field=models.CharField(default='_', max_length=500),
        ),
        migrations.AddField(
            model_name='cardiacrequested',
            name='A_3B_name',
            field=models.CharField(default='Blood transfusion Set', max_length=500),
        ),
        migrations.AddField(
            model_name='cardiacrequested',
            name='A_3B_qty',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='cardiacrequested',
            name='A_1_name',
            field=models.CharField(default='ACT Tubes', max_length=500),
        ),
        migrations.AlterField(
            model_name='cardiacrequested',
            name='A_2A_name',
            field=models.CharField(default='Arterial line cannula (Adult)', max_length=500),
        ),
        migrations.AlterField(
            model_name='cardiacrequested',
            name='A_2B_name',
            field=models.CharField(default='Arterial line cannula (Pediatric)', max_length=500),
        ),
        migrations.AlterField(
            model_name='cardiacrequested',
            name='A_4_name',
            field=models.CharField(default='BIS Sensor', max_length=500),
        ),
        migrations.AlterField(
            model_name='cardiacrequested',
            name='A_5_name',
            field=models.CharField(default='Bronchial blocker', max_length=500),
        ),
        migrations.AlterField(
            model_name='requests',
            name='createdby',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
