# Generated by Django 3.1.7 on 2021-04-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='patientname',
            field=models.CharField(default='Patient', max_length=100),
        ),
        migrations.AddField(
            model_name='requests',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='requests',
            name='createdby',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
