# Generated by Django 3.1.7 on 2021-04-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210416_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardiacrequested',
            name='id',
        ),
        migrations.AlterField(
            model_name='cardiacrequested',
            name='docnumber',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
