# Generated by Django 3.1.7 on 2021-04-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210416_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardiacrequested',
            name='docnumber',
            field=models.CharField(default='_', max_length=100, primary_key=True, serialize=False),
        ),
    ]
