# Generated by Django 3.1.7 on 2021-03-16 14:46

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cardiacrequested_request'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', api.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
        migrations.AlterField(
            model_name='requests',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='requests',
            name='weight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='yo', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
