# Generated by Django 3.1.7 on 2021-04-03 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210403_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='status',
            new_name='state',
        ),
    ]
