# Generated by Django 3.1.7 on 2021-04-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210402_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardiacrequested',
            name='A_1_qty',
            field=models.CharField(blank=True, default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='cardiacrequested',
            name='A_2B_qty',
            field=models.CharField(blank=True, default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='cardiacrequested',
            name='A_3A_qty',
            field=models.CharField(blank=True, default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='cardiacrequested',
            name='A_3B_qty',
            field=models.CharField(blank=True, default='0', max_length=100),
        ),
    ]
