# Generated by Django 3.1.7 on 2021-04-04 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210402_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardiacrequested',
            old_name='request',
            new_name='docnumber',
        ),
    ]
