# Generated by Django 3.1.7 on 2021-04-05 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210404_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='wardadhaar',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(12), django.core.validators.MaxLengthValidator(12)]),
        ),
        migrations.AlterField(
            model_name='requests',
            name='wardadhaar',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(12), django.core.validators.MaxLengthValidator(12)]),
        ),
    ]
