# Generated by Django 3.1.7 on 2021-04-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210406_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='state',
            field=models.CharField(default='Approved', max_length=100),
        ),
    ]
