# Generated by Django 3.1.7 on 2021-04-05 20:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_requests_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='wardadhaar',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(100000000000), django.core.validators.MaxValueValidator(999999999999)]),
        ),
        migrations.AlterField(
            model_name='requests',
            name='wardadhaar',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(100000000000), django.core.validators.MaxValueValidator(999999999999)]),
        ),
    ]
